model_list:
  - model_name: claude-sonnet-4.6
    litellm_params:
      model: github_copilot/claude-sonnet-4.6
      extra_headers:
        {
          "Editor-Version": "vscode/1.109.5",
          "Copilot-Integration-Id": "vscode-chat",
        }
      drop_params: true

  - model_name: claude-haiku-4.5
    litellm_params:
      model: github_copilot/claude-haiku-4.5
      extra_headers:
        {
          "Editor-Version": "vscode/1.109.5",
          "Copilot-Integration-Id": "vscode-chat",
        }

  - model_name: claude-opus-4.6
    litellm_params:
      model: github_copilot/claude-opus-4.6
      extra_headers:
        {
          "Editor-Version": "vscode/1.109.5",
          "Copilot-Integration-Id": "vscode-chat",
        }
      drop_params: true

